### ISSUE TITLE
can't understand the concept of sockets in PhoneRTC

### ISSUE THREAD

**Issue by selvaece25** [dhirajbodicherla/phonertc-demo#1]
just to make sure, TURN server is strictly required or optional?

If it required means can you provide  following steps to install it on AWS

At the top of the html page you are include the following line:

 <script type="text/javascript" src="https://phonertc-sample-c9-dhirajbodicherla.c9.io/socket.io/socket.io.js"></script>

var socket = io.connect('https://phonertc-sample-c9-dhirajbodicherla.c9.io/'),
                session, username, callingTo, duplicateMessages = [];

Can you explaining a bit more what you mean by above lines.

Thank you

**Comment by selvaece25** [comment]
When I run the demo application on Android its simply showing List of users only Any idea what is going wrong?

**Comment by dhirajbodicherla** [comment]
@selvaece25 TURN server is NOT optional. I did not install it on AWS but i'll see if I can provide steps.
`var socket = io.connect('https://phonertc-sample-c9-dhirajbodicherla.c9.io/')`
The above link creates a connection with your signaling sever. I am using socket.io as signaling server and I hosted it on `https://phonertc-sample-c9..`

Regarding the empty list of users, my server was down and hence you saw empty list. It's up and running now. It should work.

**Comment by selvaece25** [comment]
How could i use the  socket.io as signaling server  in my domain can you please help on that.

**Comment by dhirajbodicherla** [comment]
Hope this helps http://www.html5rocks.com/en/tutorials/webrtc/basics/

**Comment by Dhanashri04** [comment]
i am getting black screen instead of user video call face. why this issue? i am able to call to other user and also can receive call as well but not able to see user face only black box is appearing .please help
